<?php

namespace VoyageBundle\Repository;

/**
 * ReclamationVoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationVoyageRepository extends \Doctrine\ORM\EntityRepository
{
}
