<?php

namespace VoyageBundle\Repository;

use Proxies\__CG__\VoyageBundle\Entity\ReclamationVoyage;

/**
 * ReclamationVoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationVoyageRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeRecVoy($RecVoy)
    {
        $this->getEntityManager()->remove($RecVoy);
        $this->getEntityManager()->flush();
    }
}
