services:
#    voyage.example:
#        class: VoyageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  voyage.Voyage.new:
    class: VoyageBundle\Command\VoyageSmsCommand
    tags:
      - { name: 'consoel.command' , command: 'Voyage:sms' }

  twilio.client:
    class: Twilio\Rest\Client
    arguments: ['%twilio_sid%', '%twilio_token%']

  # Add an alias for the twilio.client service
  Twilio\Rest\Client: '@twilio.client'

