reservation_colis:
    resource: "@ReservationBundle/Controller/ColisController.php"
    type:     annotation

reservation_reservation_business:
    resource: "@ReservationBundle/Controller/ReservationBusinessController.php"
    type:     annotation

reservation_reservation:
    resource: "@ReservationBundle/Controller/ReservationController.php"
    type:     annotation

voyage:
    resource: "@VoyageBundle/Resources/config/routing.yml"
    prefix:   /Voyage

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /Reclamation

promotion:
    resource: "@PromotionBundle/Resources/config/routing.yml"
    prefix:   /Promotion

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /News

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /Reservation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


app:
    resource: '@AppBundle/Controller/'
    type: annotation

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
