voyage:
    resource: "@VoyageBundle/Resources/config/routing.yml"
    prefix:   /Voyage

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /Reclamation

promotion:
    resource: "@PromotionBundle/Resources/config/routing.yml"
    prefix:   /Promotion

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /News

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /Reservation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

loginMobile:
    path:     /loginMobile/{username}/{password}
    defaults: { _controller: AppBundle:Default:loginMobile }
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
