<?php

namespace NewsBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n
                FROM NewsBundle:News n
                WHERE n.titre LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function three(){
        $q= $this->getEntityManager()->createQuery('SELECT n FROM NewsBundle:News n ORDER BY n.id DESC LIMIT 3');
        return $q->getResult();
    }


}
