<?php

namespace ReservationBundle\Repository;

use VoyageBundle\Entity\Voyage;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
