<?php

namespace ReservationBundle\Repository;

/**
 * ReservationBusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationBusinessRepository extends \Doctrine\ORM\EntityRepository
{
}
