reservation_homepage:
    path:     /
    defaults: { _controller: ReservationBundle:Default:index }

bonour:
    path:     /bn
    defaults: { _controller: ReservationBundle:Reservation:bn }

ajout:
    path:     /add
    defaults: { _controller: ReservationBundle:Reservation:new }

affiche:
    path:     /list
    defaults: { _controller: ReservationBundle:Reservation:index }