reservation_homepage:
    path:     /
    defaults: { _controller: ReservationBundle:Default:index }

bonour:
    path:     /bn
    defaults: { _controller: ReservationBundle:Reservation:bn }

new:
    path:     /reservation_new
    defaults: { _controller: ReservationBundle:Reservation:new }

index:
    path:     /reservation_index
    defaults: { _controller: ReservationBundle:Reservation:index }

show:
    path:     /reservation_show/{Id}
    defaults: { _controller: ReservationBundle:Reservation:show }

edit:
    path:     /reservation_edit
    defaults: { _controller: ReservationBundle:Reservation:edit }

delete:
    path:     /reservation_delete/{id}
    defaults: { _controller: ReservationBundle:Reservation:delete }

root:
    path:     /root
    defaults: { _controller: ReservationBundle:Reservation:root }

rootpassager:
    path:     /rootpassager
    defaults: { _controller: ReservationBundle:Reservation:rootpassager }

newbusiness:
    path:     /reservationbusiness_new
    defaults: { _controller: ReservationBundle:ReservationBusiness:new }

indexbusiness:
    path:     /reservationbusiness_index
    defaults: { _controller: ReservationBundle:ReservationBusiness:index }

showbusiness:
    path:     /reservationbusiness_show/{idResBusiness}
    defaults: { _controller: ReservationBundle:ReservationBusiness:show }

editbusiness:
    path:     /reservationbusiness_edit
    defaults: { _controller: ReservationBundle:ReservationBusiness:edit }

newcolis:
    path:     /colis_index
    defaults: { _controller: ReservationBundle:Colis:index }

indexcolis:
    path:     /colis_new
    defaults: { _controller: ReservationBundle:Colis:new }

showcolis:
    path:     /colis_show/{idColis}
    defaults: { _controller: ReservationBundle:Colis:show }

editcolis:
    path:     /colis_edit/{idColis}
    defaults: { _controller: ReservationBundle:Colis:edit }

deletecolis:
    path:     /colis_delete/{idColis}
    defaults: { _controller: ReservationBundle:Colis:delete }

listereservations:
    path:   /listereservations
    defaults: { _controller: ReservationBundle:Admin:afficherlistereservations}

listeusers:
    path:   /listeusers
    defaults: { _controller: ReservationBundle:Admin:afficherlisteusers}

listebusiness:
    path:   /listebusiness
    defaults: { _controller: ReservationBundle:Admin:afficherlistebusiness}

deletecolisss:
    path:   /delete/{id}
    defaults: { _controller: ReservationBundle:Colis:deleteColis}

traiterbusiness:
    path:   /traiter/{idResBusiness}
    defaults: { _controller: ReservationBundle:Admin:traitement}

convertirbusiness:
    path:   /convertir/{idResBusiness}/{prix}/{chauffeur}
    defaults: { _controller: ReservationBundle:Admin:convertir}

calend:
    path:   /calendrier
    defaults: { _controller: ReservationBundle:Admin:calendrier}

alljson:
    path:   /all
    defaults: { _controller: ReservationBundle:Reservation:all}

ajouterjson:
    path:   /ajouter
    defaults: { _controller: ReservationBundle:Reservation:ajouter}

modifierjson:
    path:   /modifier
    defaults: { _controller: ReservationBundle:Reservation:modifier}

supprimerjson:
    path:   /supprimerreservation
    defaults: { _controller: ReservationBundle:Reservation:supprimerjson}


allusersjson:
    path:   /allusers
    defaults: { _controller: AppBundle:Default:allusers}

allbusinessjson:
    path:   /allbusiness
    defaults: { _controller: ReservationBundle:ReservationBusiness:allbusiness}

ajouterbusinessjson:
    path:   /ajouterbusiness
    defaults: { _controller: ReservationBundle:ReservationBusiness:ajouterbusiness}

supprimerbusinessjson:
    path:   /supprimerbusiness
    defaults: { _controller: ReservationBundle:ReservationBusiness:supprimerbusiness}

modifierbusinessjson:
    path:   /modifierbus
    defaults: { _controller: ReservationBundle:ReservationBusiness:modifierbusiness}

mail:
    path: /envoyermail
    defaults: { _controller: ReservationBundle:Admin:mail}