reservation_homepage:
    path:     /
    defaults: { _controller: ReservationBundle:Default:index }

bonour:
    path:     /bn
    defaults: { _controller: ReservationBundle:Reservation:bn }

new:
    path:     /reservation_new
    defaults: { _controller: ReservationBundle:Reservation:new }

index:
    path:     /reservation_index
    defaults: { _controller: ReservationBundle:Reservation:index }

show:
    path:     /reservation_show/{Id}
    defaults: { _controller: ReservationBundle:Reservation:show }

edit:
    path:     /reservation_edit
    defaults: { _controller: ReservationBundle:Reservation:edit }

delete:
    path:     /reservation_delete
    defaults: { _controller: ReservationBundle:Reservation:delete }

root:
    path:     /root
    defaults: { _controller: ReservationBundle:Reservation:root }

newbusiness:
    path:     /reservationbusiness_new
    defaults: { _controller: ReservationBundle:ReservationBusiness:new }

indexbusiness:
    path:     /reservationbusiness_index
    defaults: { _controller: ReservationBundle:ReservationBusiness:index }

showbusiness:
    path:     /reservationbusiness_show/{idResBusiness}
    defaults: { _controller: ReservationBundle:ReservationBusiness:show }

editbusiness:
    path:     /reservationbusiness_edit
    defaults: { _controller: ReservationBundle:ReservationBusiness:edit }